### ISSUE TITLE
Cadastro de usuário na plataforma

### ISSUE THREAD

**Issue by Marlysson** [Marlysson/Project-Manager#4]
Usando Class Based Views

**Comment by Marlysson** [comment]
Aqui cabe uma discussão.

**Inicialmente seria:**

- Usuário se cadastra para poder ter todo o fluxo de autenticação e permissões dentro da app
- Se um gerente for adicionar uma pessoa no projeto ele poderia pesquisar a pessoa na app toda ( parecido com o trello )

**Mudando um pouco:**

- O gerente poderia cadastrar o usuário e o usuário ficar só naquela empresa no app

**Discussão:**

Cria usuário geral e também times e quando o gerente adicionar no time, primeiro busca nos times criados e depois nos usuários da plaaforma....

**Comment by rg3915** [comment]
* Cadastro padrão de um usuário, usando [CBV](http://ccbv.co.uk/), considere que isso é um usuário comum, ou seja, qualquer pessoa que pode se auto cadastrar.
